### ISSUE TITLE
Integrate puppeteer and other depended files in the sandbox

### ISSUE THREAD

**Issue by sudev-git** [shah/engineering-sandbox-debian#10]
In order to run the puppeteer headless chrome, we need Puppeteer and chromedriver in the workspace. We have added the commands in [README.md](https://git.netspective.io/netspective-medigy/properties/orchestrator/-/tree/master/automation-scripts-using-headless-chrome#install-puppeteer-for-the-first-time). Please integrate them in sandbox.

**Comment by prathithacb** [comment]
I'm closing this ticket since not all developers/content/etc. need this, and NPM is already part of the sandbox, the devs/testers that do need puppeteer should just run it manually.
Also, will make sure to add Puppeteer-based tests into CI/CD for devl.medigy.com so that the output of test cases are pushed to Prometheus after each build.

**Comment by sudev-git** [comment]
I am OK with the above comment and closing this ticket.
